wandb: {}
project_name: train_HILC_sceneflow_v0
restore_ckpt: "/DATA/i2r/guzw/workspace/DepthStereo/MonSter/checkpoints/ft_sceneflow_MoNIG_consistency_fp16_v4/40000.pth"
logdir: './checkpoints/train_HILC_sceneflow_v0/'
encoder: 'vitl'
batch_size: 8
train_datasets: ['sceneflow']
lr: 1e-4
wdecay: 1e-5
total_step: 40000
save_frequency: 4000
save_path: ./checkpoints/train_HILC_sceneflow_v0/
val_frequency: 2000
image_size: [320, 736]
train_iters: 22
valid_iters: 32
val_dataset: 'kitti'
corr_implementation: "reg"
corr_levels: 2
corr_radius: 4
n_downsample: 2
n_gru_layers: 3
hidden_dims: [128, 128, 128]
max_disp: 192
saturation_range: [0.7, 1.3]
do_flip: False
spatial_scale: [-0.2, 0.5]
noyjitter: True
num_gpu: 4
seed: 666
